### ISSUE TITLE
console.log files only update after game exits?

### ISSUE THREAD

**Issue by RylanSchaeffer** [TamaMcGlinn/dotfiles#1]
I noticed you have two aliases for reading log files:

```
alias emp_logs='tail -f ~/.steam/steam/steamapps/common/Empires/empires/console.log'
alias emp_dev_logs='tail -f ~/code/empires/empires_base/mp/game/empires/console.log'
```

When I try this with Dota 2, I run into the issue that the console.log file is only written to after the game process exits. Did you have the same issue? If so, how did you fix it?

**Comment by TamaMcGlinn** [comment]
Interesting; I didn't have that problem, but that may be due to how you start the game. I describe this alias more fully on the empiresmod website, [here](http://www.empiresmod.com/posts/2016-11-03-tailing-source.html).

**Comment by TamaMcGlinn** [comment]
Did you pass ` -condebug ` to the game?
Oh, btw, the two aliases are due to one being for use with the debugger and the other when run from Steam.
